# ~/.config/nvim/.stylua.toml
# ------------------------------------------------------------------
# 1. Core style ----------------------------------------------------------------
column_width              = 160                 # wrap guide (≈ not a hard limit)
indent_type               = "Spaces"            # "Tabs" | "Spaces"
indent_width              = 4                   # size of one indent level
line_endings              = "Unix"              # "Unix" (LF) | "Windows" (CRLF)
quote_style               = "AutoPreferDouble"  # Personally prefer "" over ''
call_parentheses          = "NoSingleTable"     # keeps DSL-ish code tidy
collapse_simple_statement = "FunctionOnly"      # one-liners for tiny funcs

# 2. Language flavour ----------------------------------------------------------
# Only set this if you *need* to disambiguate mixed Lua/Luau/Cfx etc.
# syntax = "Lua54"        # "All" (default) | Lua51 | Lua52 | Lua53 | Lua54 | LuaJIT | Luau | CfxLua

# 3. Extras --------------------------------------------------------------------
[sort_requires]           # opt-in helper that alphabetises `local X = require(...)`
enabled = true
# ------------------------------------------------------------------
