unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded!"    # Reload config on <prefix> r

set -g mouse on                                           # Enable mouse
set -g set-clipboard on                                   # Integrate with system clipboard
set -g base-index 1                                       # Start indexing windows from 1
set -g history-limit 10000                                 # Increase history size from 2,000
set -g renumber-windows on                                # Renumber windows on close
set -g default-terminal "tmux-256color"                   # True color support
set -as terminal-features ",xterm*:RGB"                   # True color support
set -s escape-time 0                                      # No delay after <Esc> key
set -g status-interval 3                                  # Update bar every 3 sec (default: 15)
set -s extended-keys on                                   # Let Ctrl+, Shift+, etc combinations work
set -as terminal-features ",xterm*:extkeys"               # Let Ctrl+, Shift+, etc combinations work
set -g focus-events on                                    # Let programs detect pane focus changes
set -as terminal-overrides ",*:Smulx=\E[4::%p1%dm"        # Undercurl support
set -as terminal-overrides ",*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m" # Underline colors

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
# bind-key -T copy-mode-vi 'C-\' select-pane -l

# Simple home made Catppuccin styling
text="#cdd6f4"
surface="#313244"
green="#a6e3a1"
mauve="#cba6f7"
blue="#89b4fa"
lavender="#b4befe"

set -g status-position top
set -g status-left-length 100
set -g status-right-length 100
set -g automatic-rename-format "#{b:pane_current_path}"
set -g status-style "fg=${text},bg=default"
set -g status-left " #[fg=${green},bold][  #{s/\\$//:session_id}:#S ] "
set -g status-right "#[fg=${blue},bold] #{s|$HOME|~|:pane_current_path} #[fg=${lavender}] #(whoami)@#h "
set -g window-status-current-format "#[fg=${mauve},bold]() #{?window_zoomed_flag, ,}#I:#W"
set -g window-status-format " #[fg=${text}]#I:#W"
set -g message-style "fg=${text},bg=default"
set -g mode-style "fg=${surface},bg=${blue}"
set -g pane-border-style "fg=${surface}"
set -g pane-active-border-style "fg=${green}"
